version: "3.7"

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: m@st$rcod$r!
    ports:
      - "27017:27017"
    volumes:
      - ~/.docker-conf/mongo/data/:/data/db
    networks:
      - master-coder-net

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - master-coder-net

  api-gateway:
    container_name: api-gateway
    build:
      context: ./api-gateway .
      target: development
    volumes:
      - ./api-gateway/src
      - ./api-gateway/src/node_modules
    ports:
      - 3010:3010
    command: npm run start:dev
    env_file:
      - ./api-gateway/.env
    networks:
      - master-coder-net

  api-profile:
    container_name: api-profile
    build:
      context: ./api-profile .
      target: development
    volumes:
      - ./api-profile/src
      - ./api-profile/src/node_modules
    ports:
      - 3020:3020
    command: npm run start:dev
    env_file:
      - ./api-profile/.env
    networks:
      - master-coder-net

  api-certification:
    container_name: api-certification
    build:
      context: ./api-certification .
      target: development
    volumes:
      - ./api-certification/src
      - ./api-certification/src/node_modules
    ports:
      - 3030:3030
    command: npm run start:dev
    env_file:
      - ./api-certification/.env
    networks:
      - master-coder-net

  api-community:
    container_name: api-community
    build:
      context: ./api-community .
      target: development
    volumes:
      - ./api-community/src
      - ./api-community/src/node_modules
    ports:
      - 3040:3040
    command: npm run start:dev
    env_file:
      - ./api-community/.env
    networks:
      - master-coder-net

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: mastercoder
      ME_CONFIG_BASICAUTH_PASSWORD: m@st$rcod$r!
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: m@st$rcod$r!
    links:
      - mongo
    networks:
      - master-coder-net
    depends_on:
      - mongo

networks:
  master-coder-net:
    driver: bridge
