version: "3.7"

services:
  main:
    container_name: api-gateway
    build:
      context: ./api-gateway .
      target: development
    volumes:
      - ./api-gateway/src
      - ./api-gateway/src/node_modules
    ports:
      - 3010:3010
    command: npm run start:dev
    env_file:
      - ./api-gateway/.env
    networks:
      - master-coder-net
networks:
  master-coder-net:
